name: Générer articles.json

on:
  push:
    paths:
      - 'post/*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Installer dépendances
        run: npm install gray-matter

      - name: Générer articles.json
        run: node generate-articles-json.js  # ✅ on exécute depuis un vrai fichier

      - name: Commit et push
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add articles.json
          git commit -m "Mise à jour auto de articles.json" || echo "Pas de changement"
          git push

