name: Générer articles.json

on:
  push:
    paths:
      - 'post/*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Installer dépendances
        run: npm install gray-matter

      - name: Générer articles.json
        run: |
          node <<EOF
          const fs = require("fs");
          const matter = require("gray-matter");
          const articles = [];

          fs.readdirSync("./post").forEach(file => {
            if (file.endsWith(".md")) {
              const raw = fs.readFileSync("./post/" + file, "utf8");
              const { data, content } = matter(raw);
              const excerpt = content.trim().split("\n").slice(0, 5).join(" ");
              articles.push({
                id: data.id,
                title: data.title,
                date: data.date,
                image: "https://pastoa.github.io/actualites/" + data.image,
                slug: file.replace(".md", ""),
                excerpt: excerpt
                content: html
              });
            }
          });

          articles.sort((a, b) => new Date(b.date) - new Date(a.date));
          fs.writeFileSync("articles.json", JSON.stringify(articles, null, 2));
          EOF

      - name: Commit et push
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add articles.json
          git commit -m "Mise à jour auto de articles.json" || echo "Pas de changement"
          git push
